added eslint rules
MIKZON/rails-project pull request #21
Opened 2021-05-17 15:53 UTC by MIKZON

2021-05-17 18:35 UTC, greybutton requested changes

2021-05-17 18:35 UTC, greybutton commented on app/javascript/packs/hello_react.jsx
> +// Run this example by adding <%= javascript_pack_tag 'hello_react' %> to the head of your layout file,
этот файл нужно удалить

2021-05-23 17:56 UTC, MIKZON commented on app/javascript/packs/hello_react.jsx
> +// Run this example by adding <%= javascript_pack_tag 'hello_react' %> to the head of your layout file,
Удалил его в другой ветке, которая следом идёт от этой ветки https://github.com/MIKZON/rails-project/commit/715b880a3daed4137d124a6b83540c098fd43799

2021-05-24 07:34 UTC, greybutton approved these changes

2021-05-24 12:15 UTC, merged